"""
AI Image Classifier — PROTOTYPE / MOCK IMPLEMENTATION
======================================================
This is a clearly-labeled prototype classifier.
It does NOT use a real trained model.
The architecture is designed for drop-in replacement with YOLO v8,
ResNet, or MobileNet once training data is available.

All predictions are labeled with is_mock=True and a disclaimer.
"""
import random
import hashlib
from typing import Optional
from dataclasses import dataclass


CATEGORY_KEYWORDS = {
    "pothole": ["pothole", "hole", "pit", "crater", "road damage", "depression"],
    "garbage": ["garbage", "trash", "waste", "litter", "dump", "rubbish", "debris"],
    "water_leakage": ["water", "leak", "pipe", "flood", "overflow", "drain", "waterlog"],
    "broken_streetlight": ["light", "streetlight", "lamp", "dark", "bulb", "electric"],
    "damaged_road": ["road", "crack", "broken", "damaged", "pavement", "asphalt", "highway"],
}

CATEGORY_SEVERITY_MAP = {
    "pothole": "high",
    "garbage": "medium",
    "water_leakage": "high",
    "broken_streetlight": "medium",
    "damaged_road": "high",
}


@dataclass
class ClassificationResult:
    category: str
    confidence: float
    severity: str
    is_mock: bool = True
    disclaimer: str = (
        "⚠️ PROTOTYPE INFERENCE — This classification is generated by a "
        "rule-based mock system, not a trained AI model. "
        "Results are for demonstration purposes only."
    )


class AIClassifier:
    """
    Base class for civic issue classification.
    Replace _classify_image() with real model inference (YOLO/ResNet)
    without changing any other code.
    """

    def classify(
        self,
        image_path: Optional[str] = None,
        description: Optional[str] = None,
        filename: Optional[str] = None,
    ) -> ClassificationResult:
        """Main entry point. Combines image + text signals."""
        # Derive a deterministic seed so same input → same output
        seed_str = (image_path or "") + (description or "") + (filename or "")
        seed = int(hashlib.md5(seed_str.encode()).hexdigest()[:8], 16)
        rng = random.Random(seed)

        category = self._classify_from_text(description, filename, rng)
        confidence = self._estimate_confidence(rng)
        severity = CATEGORY_SEVERITY_MAP.get(category, "medium")

        return ClassificationResult(
            category=category,
            confidence=confidence,
            severity=severity,
        )

    def _classify_from_text(self, description: Optional[str], filename: Optional[str], rng: random.Random) -> str:
        """Rule-based category detection from text signals."""
        combined = ((description or "") + " " + (filename or "")).lower()

        scores: dict[str, int] = {cat: 0 for cat in CATEGORY_KEYWORDS}
        for category, keywords in CATEGORY_KEYWORDS.items():
            for kw in keywords:
                if kw in combined:
                    scores[category] += 1

        best = max(scores, key=lambda c: scores[c])
        if scores[best] == 0:
            # No text match → random weighted selection for demo
            best = rng.choice(list(CATEGORY_KEYWORDS.keys()))

        return best

    def _estimate_confidence(self, rng: random.Random) -> float:
        """Returns a realistic-looking confidence score (0.72 - 0.97)."""
        return round(rng.uniform(0.72, 0.97), 2)


# Singleton instance
classifier = AIClassifier()
