import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export interface Language {
  code: string
  name: string
  nativeName: string
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
]

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    tagline: '— Mera Shehar, Meri Awaaz, Hamara Badlav —',
    subtagline: 'See it. Report it. Fix it.',
    citizen: 'Citizen',
    register: 'Register',
    officer: 'Officer',
    login: 'Login',
    create_account: 'Create Account',
    officer_login: 'Officer Login',
    email_or_phone: 'Email or Mobile Number',
    password: 'Password',
    full_name: 'Full Name',
    ward_area: 'Ward / Area',
    enter_password: 'Enter your password',
    report_problem: 'REPORT A PROBLEM',
    report_desc: 'Photo • Location • Description',
    my_reports: 'My Reports',
    nearby_issues: 'Nearby Issues',
    safety_sos: 'Safety SOS',
    settings: 'Settings',
    logout: 'Logout',
    whats_wrong: "What's wrong in your area?",
    recent_issues: 'Recent Issues Near You',
    view_all: 'View all',
    select_language: 'Select Language',
    profile: 'Profile',
    activity: 'My Activity',
    preferences: 'Preferences',
    account: 'Account',
    language: 'Language',
    notifications: 'Notifications',
    privacy: 'Privacy Settings',
    edit_profile: 'Edit Profile',
    change_password: 'Change Password',
    sos_history: 'SOS & Safety History',
  },
  mr: {
    tagline: '— माझे शहर, माझा आवाज, आमचा बदल —',
    subtagline: 'पाहा. नोंदवा. सोडवा.',
    citizen: 'नागरिक',
    register: 'नोंदणी',
    officer: 'अधिकारी',
    login: 'लॉगिन करा',
    create_account: 'खाते तयार करा',
    officer_login: 'अधिकारी लॉगिन',
    email_or_phone: 'ईमेल किंवा मोबाईल नंबर',
    password: 'पासवर्ड',
    full_name: 'पूर्ण नाव',
    ward_area: 'प्रभाग / परिसर',
    enter_password: 'पासवर्ड टाका',
    report_problem: 'समस्या नोंदवा',
    report_desc: 'फोटो • स्थान • तपशील',
    my_reports: 'माझ्या तक्रारी',
    nearby_issues: 'परिसरातील समस्या',
    safety_sos: 'महिला सुरक्षा SOS',
    settings: 'सेटिंग्ज',
    logout: 'लॉगआउट',
    whats_wrong: 'आपल्या भागात काय समस्या आहे?',
    recent_issues: 'परिसरातील अलीकडील समस्या',
    view_all: 'सर्व पाहा',
    select_language: 'भाषा निवडा',
    profile: 'प्रोफाइल',
    activity: 'माझी कृती',
    preferences: 'प्राधान्ये',
    account: 'खाते',
    language: 'भाषा',
    notifications: 'सूचना',
    privacy: 'गोपनीयता',
    edit_profile: 'प्रोफाइल बदला',
    change_password: 'पासवर्ड बदला',
    sos_history: 'SOS आणि सुरक्षा इतिहास',
  },
  hi: {
    tagline: '— मेरा शहर, मेरी आवाज़, हमारा बदलाव —',
    subtagline: 'देखें. रिपोर्ट करें. समाधान पाएं.',
    citizen: 'नागरिक',
    register: 'पंजीकरण',
    officer: 'अधिकारी',
    login: 'लॉग इन करें',
    create_account: 'खाता बनाएं',
    officer_login: 'अधिकारी लॉगिन',
    email_or_phone: 'ईमेल या मोबाइल नंबर',
    password: 'पासवर्ड',
    full_name: 'पूरा नाम',
    ward_area: 'वार्ड / क्षेत्र',
    enter_password: 'पासवर्ड दर्ज करें',
    report_problem: 'समस्या रिपोर्ट करें',
    report_desc: 'फ़ोटो • स्थान • विवरण',
    my_reports: 'मेरी रिपोर्ट',
    nearby_issues: 'आस-पास की समस्याएं',
    safety_sos: 'महिला सुरक्षा SOS',
    settings: 'सेटिंग्स',
    logout: 'लॉगआउट',
    whats_wrong: 'आपके क्षेत्र में क्या समस्या है?',
    recent_issues: 'आस-पास की हालिया समस्याएं',
    view_all: 'सभी देखें',
    select_language: 'भाषा चुनें',
    profile: 'प्रोफ़ाइल',
    activity: 'मेरी गतिविधि',
    preferences: 'प्राथमिकताएं',
    account: 'खाता',
    language: 'भाषा',
    notifications: 'सूचनाएं',
    privacy: 'गोपनीयता सेटिंग्स',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    change_password: 'पासवर्ड बदलें',
    sos_history: 'SOS और सुरक्षा इतिहास',
  },
  gu: {
    tagline: '— મારું શહેર, મારો અવાજ, આપણો બદલાવ —',
    subtagline: 'જુઓ. રિપોર્ટ કરો. ઉકેલ લાવો.',
    citizen: 'નાગરિક',
    register: 'નોંધણી',
    officer: 'અધિકારી',
    login: 'લૉગિન કરો',
    create_account: 'ખાતું બનાવો',
    officer_login: 'અધિકારી લૉગિન',
    email_or_phone: 'ઈમેલ અથવા મોબાઈલ નંબર',
    password: 'પાસવર્ડ',
    full_name: 'પૂરું નામ',
    ward_area: 'વૉર્ડ / વિસ્તાર',
    enter_password: 'પાસવર્ડ દાખલ કરો',
    report_problem: 'સમસ્યા રિપોર્ટ કરો',
    report_desc: 'ફોટો • સ્થળ • વિગત',
    my_reports: 'મારી ફરિયાદો',
    nearby_issues: 'નજીકની સમસ્યાઓ',
    safety_sos: 'મહિલા સુરક્ષા SOS',
    settings: 'સેટિંગ્સ',
    logout: 'લૉગઆઉટ',
    whats_wrong: 'તમારા વિસ્તારમાં શું સમસ્યા છે?',
    recent_issues: 'નજીકની તાજેતરની સમસ્યાઓ',
    view_all: 'બધું જુઓ',
    select_language: 'ભાષા પસંદ કરો',
    profile: 'પ્રોફાઇલ',
    activity: 'મારી પ્રવૃત્તિ',
    preferences: 'પસંદગીઓ',
    account: 'ખાતું',
    language: 'ભાષા',
    notifications: 'સૂચનાઓ',
    privacy: 'ગોપનીયતા',
    edit_profile: 'પ્રોફાઇલ સંપાદિત કરો',
    change_password: 'પાસવર્ડ બદલો',
    sos_history: 'SOS ઇતિહાસ',
  },
  bn: {
    tagline: '— আমার শহর, আমার কণ্ঠ, আমাদের পরিবর্তন —',
    subtagline: 'দেখুন. অভিযোগ করুন. সমাধান পান.',
    citizen: 'নাগরিক',
    register: 'নিবন্ধন',
    officer: 'কর্মকর্তা',
    login: 'লগইন করুন',
    create_account: 'অ্যাকাউন্ট তৈরি করুন',
    officer_login: 'অফিসার লগইন',
    email_or_phone: 'ইমেল বা মোবাইল নম্বর',
    password: 'পাসওয়ার্ড',
    full_name: 'সম্পূর্ণ নাম',
    ward_area: 'ওয়ার্ড / এলাকা',
    enter_password: 'পাসওয়ার্ড লিখুন',
    report_problem: 'সমস্যা রিপোর্ট করুন',
    report_desc: 'ছবি • অবস্থান • বিবরণ',
    my_reports: 'আমার রিপোর্ট',
    nearby_issues: 'কাছের সমস্যাসমূহ',
    safety_sos: 'নারী সুরক্ষা SOS',
    settings: 'সেটিংস',
    logout: 'লগআউট',
    whats_wrong: 'আপনার এলাকায় কি সমস্যা?',
    recent_issues: 'নিকটবর্তী সাম্প্রতিক সমস্যা',
    view_all: 'সব দেখুন',
    select_language: 'ভাষা নির্বাচন করুন',
    profile: 'প্রোফাইল',
    activity: 'আমার কার্যকলাপ',
    preferences: 'পছন্দসমূহ',
    account: 'অ্যাকাউন্ট',
    language: 'ভাষা',
    notifications: 'বিজ্ঞপ্তি',
    privacy: 'গোপনীয়তা',
    edit_profile: 'প্রোফাইল সম্পাদনা',
    change_password: 'পাসওয়ার্ড পরিবর্তন',
    sos_history: 'SOS ইতিহাস',
  },
  ta: {
    tagline: '— என் நகரம், என் குரல், நமது மாற்றம் —',
    subtagline: 'பாருங்கள். புகாரளியுங்கள். தீர்வு காணுங்கள்.',
    citizen: 'குடிமகன்',
    register: 'பதிவு செய்',
    officer: 'அதிகாரி',
    login: 'உள்நுழைக',
    create_account: 'கணக்கை உருவாக்கு',
    officer_login: 'அதிகாரி உள்நுழைவு',
    email_or_phone: 'மின்னஞ்சல் அல்லது மொபைல் எண்',
    password: 'கடவுச்சொல்',
    full_name: 'முழு பெயர்',
    ward_area: 'வார்டு / பகுதி',
    enter_password: 'கடவுச்சொல்லை உள்ளிடவும்',
    report_problem: 'பிரச்சினையைப் புகாரளி',
    report_desc: 'புகைப்படம் • இடம் • விவரம்',
    my_reports: 'என் புகார்கள்',
    nearby_issues: 'அருகிலுள்ள பிரச்சினைகள்',
    safety_sos: 'பெண்கள் பாதுகாப்பு SOS',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    whats_wrong: 'உங்கள் பகுதியில் என்ன பிரச்சினை?',
    recent_issues: 'அருகிலுள்ள சமீபத்திய பிரச்சினைகள்',
    view_all: 'அனைத்தையும் காண்க',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    profile: 'சுயவிவரம்',
    activity: 'என் செயல்பாடு',
    preferences: 'விருப்பத்தேர்வுகள்',
    account: 'கணக்கு',
    language: 'மொழி',
    notifications: 'அறிவிப்புகள்',
    privacy: 'தனியுரிமை',
    edit_profile: 'சுயவிவரத்தைத் திருத்து',
    change_password: 'கடவுச்சொல்லை மாற்று',
    sos_history: 'SOS வரலாறு',
  },
  te: {
    tagline: '— నా నగరం, నా గళం, మన మార్పు —',
    subtagline: 'చూడండి. నివేదించండి. పరిష్కరించుకోండి.',
    citizen: 'పౌరుడు',
    register: 'నమోదు చేసుకోండి',
    officer: 'అధికారి',
    login: 'లాగిన్ అవ్వండి',
    create_account: 'ఖాతాను సృష్టించండి',
    officer_login: 'అధికారి లాగిన్',
    email_or_phone: 'ఇమెయిల్ లేదా మొబైల్ నంబర్',
    password: 'పాస్‌వర్డ్',
    full_name: 'పూర్తి పేరు',
    ward_area: 'వార్డు / ప్రాంతం',
    enter_password: 'పాస్‌వర్డ్ నమోదు చేయండి',
    report_problem: 'సమస్యను నివేదించండి',
    report_desc: 'ఫోటో • లొకేషన్ • వివరాలు',
    my_reports: 'నా నివేదికలు',
    nearby_issues: 'సమీప సమస్యలు',
    safety_sos: 'మహిళా భద్రత SOS',
    settings: 'సెట్టింగ్‌లు',
    logout: 'లాగ్ అవుట్',
    whats_wrong: 'మీ ప్రాంతంలో ఏమి సమస్య ఉంది?',
    recent_issues: 'సమీపంలోని తాజా సమస్యలు',
    view_all: 'అన్నీ చూడండి',
    select_language: 'భాషను ఎంచుకోండి',
    profile: 'ప్రొఫైల్',
    activity: 'నా కార్యాచరణ',
    preferences: 'ప్రాధాన్యతలు',
    account: 'ఖాతా',
    language: 'భాష',
    notifications: 'నోటిఫికేషన్‌లు',
    privacy: 'గోప్యత',
    edit_profile: 'ప్రొఫైల్ సవరించు',
    change_password: 'పాస్‌వర్డ్ మార్చు',
    sos_history: 'SOS చరిత్ర',
  },
  kn: {
    tagline: '— ನನ್ನ ನಗರ, ನನ್ನ ಧ್ವನಿ, ನಮ್ಮ ಬದಲಾವಣೆ —',
    subtagline: 'ನೋಡಿ. ವರದಿ ಮಾಡಿ. ಬಗೆಹರಿಸಿ.',
    citizen: 'ನಾಗರಿಕ',
    register: 'ನೋಂದಣಿ',
    officer: 'ಅಧಿಕಾರಿ',
    login: 'ಲಾಗಿನ್ ಮಾಡಿ',
    create_account: 'ಖಾತೆ ರಚಿಸಿ',
    officer_login: 'ಅಧಿಕಾರಿ ಲಾಗಿನ್',
    email_or_phone: 'ಇಮೇಲ್ ಅಥವಾ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    ward_area: 'ವಾರ್ಡ್ / ಪ್ರದೇಶ',
    enter_password: 'ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    report_problem: 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    report_desc: 'ಫೋಟೋ • ಸ್ಥಳ • ವಿವರಣೆ',
    my_reports: 'ನನ್ನ ವರದಿಗಳು',
    nearby_issues: 'ಹತ್ತಿರದ ಸಮಸ್ಯೆಗಳು',
    safety_sos: 'ಮಹಿಳಾ ಸುರಕ್ಷತೆ SOS',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    logout: 'ಲಾಗ್‌ಔಟ್',
    whats_wrong: 'ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಏನು ಸಮಸ್ಯೆ ಇದೆ?',
    recent_issues: 'ಹತ್ತಿರದ ಇತ್ತೀಚಿನ ಸಮಸ್ಯೆಗಳು',
    view_all: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    select_language: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    profile: 'ಪ್ರೊಫೈಲ್',
    activity: 'ನನ್ನ ಚಟುವಟಿಕೆ',
    preferences: 'ಆದ್ಯತೆಗಳು',
    account: 'ಖಾತೆ',
    language: 'ಭಾಷೆ',
    notifications: 'ಸೂಚನೆಗಳು',
    privacy: 'ಗೌಪ್ಯತೆ',
    edit_profile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    change_password: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
    sos_history: 'SOS ಇತಿಹಾಸ',
  },
  ml: {
    tagline: '— എന്റെ നഗരം, എന്റെ ശബ്ദം, നമ്മുടെ മാറ്റം —',
    subtagline: 'കാണുക. പരാതിപ്പെടുക. പരിഹരിക്കുക.',
    citizen: 'പൗരൻ',
    register: 'രജിസ്റ്റർ ചെയ്യുക',
    officer: 'ഉദ്യോഗസ്ഥൻ',
    login: 'ലോഗിൻ ചെയ്യുക',
    create_account: 'അക്കൗണ്ട് നിർമ്മിക്കുക',
    officer_login: 'ഓഫീസർ ലോഗിൻ',
    email_or_phone: 'ഇമെയിൽ അല്ലെങ്കിൽ മൊബൈൽ നമ്പർ',
    password: 'പാസ്‌വേഡ്',
    full_name: 'മുഴുവൻ പേര്',
    ward_area: 'വാർഡ് / പ്രദേശം',
    enter_password: 'പാസ്‌വേഡ് നൽകുക',
    report_problem: 'പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക',
    report_desc: 'ഫോട്ടോ • സ്ഥലം • വിവരണം',
    my_reports: 'എന്റെ റിപ്പോർട്ടുകൾ',
    nearby_issues: 'സമീപത്തെ പ്രശ്നങ്ങൾ',
    safety_sos: 'വനിതാ സുരക്ഷ SOS',
    settings: 'ക്രമീകരണങ്ങൾ',
    logout: 'ലോഗ്ഔട്ട്',
    whats_wrong: 'നിങ്ങളുടെ പ്രദേശത്ത് എന്താണ് പ്രശ്നം?',
    recent_issues: 'സമീപത്തെ പുതിയ പ്രശ്നങ്ങൾ',
    view_all: 'എല്ലാം കാണുക',
    select_language: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    profile: 'പ്രൊഫൈൽ',
    activity: 'എന്റെ പ്രവർത്തനം',
    preferences: 'മുൻഗണനകൾ',
    account: 'അക്കൗണ്ട്',
    language: 'ഭാഷ',
    notifications: 'അറിയിപ്പുകൾ',
    privacy: 'സ്വകാര്യത',
    edit_profile: 'പ്രൊഫൈൽ തിരുത്തുക',
    change_password: 'പാസ്‌വേഡ് മാറ്റുക',
    sos_history: 'SOS ചരിത്രം',
  },
  pa: {
    tagline: '— ਮੇਰਾ ਸ਼ਹਿਰ, ਮੇਰੀ ਆਵਾਜ਼, ਸਾਡਾ ਬਦਲਾਅ —',
    subtagline: 'ਵੇਖੋ. ਰਿਪੋਰਟ ਕਰੋ. ਹੱਲ ਕਰੋ.',
    citizen: 'ਨਾਗਰਿਕ',
    register: 'ਰਜਿਸਟਰੇਸ਼ਨ',
    officer: 'ਅਧਿਕਾਰੀ',
    login: 'ਲਾਗਇਨ ਕਰੋ',
    create_account: 'ਖਾਤਾ ਬਣਾਓ',
    officer_login: 'ਅਧਿਕਾਰੀ ਲਾਗਇਨ',
    email_or_phone: 'ਈਮੇਲ ਜਾਂ ਮੋਬਾਈਲ ਨੰਬਰ',
    password: 'ਪਾਸਵਰਡ',
    full_name: 'ਪੂਰਾ ਨਾਮ',
    ward_area: 'ਵਾਰਡ / ਇਲਾਕਾ',
    enter_password: 'ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
    report_problem: 'ਸਮੱਸਿਆ ਰਿਪੋਰਟ ਕਰੋ',
    report_desc: 'ਫੋਟੋ • ਸਥਾਨ • ਵੇਰਵਾ',
    my_reports: 'ਮੇਰੀਆਂ ਰਿਪੋਰਟਾਂ',
    nearby_issues: 'ਨੇੜਲੀਆਂ ਸਮੱਸਿਆਵਾਂ',
    safety_sos: 'ਮਹਿਲਾ ਸੁਰੱਖਿਆ SOS',
    settings: 'ਸੈਟਿੰਗਾਂ',
    logout: 'ਲਾਗਆਉਟ',
    whats_wrong: 'ਤੁਹਾਡੇ ਇਲਾਕੇ ਵਿੱਚ ਕੀ ਸਮੱਸਿਆ ਹੈ?',
    recent_issues: 'ਨੇੜਲੀਆਂ ਤਾਜ਼ਾ ਸਮੱਸਿਆਵਾਂ',
    view_all: 'ਸਭ ਵੇਖੋ',
    select_language: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    activity: 'ਮੇਰੀ ਗਤੀਵਿਧੀ',
    preferences: 'ਤਰਜੀਹਾਂ',
    account: 'ਖਾਤਾ',
    language: 'ਭਾਸ਼ਾ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    privacy: 'ਗੋਪਨੀਯਤਾ',
    edit_profile: 'ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਿਤ ਕਰੋ',
    change_password: 'ਪਾਸਵਰਡ ਬਦਲੋ',
    sos_history: 'SOS ਇਤਿਹਾਸ',
  },
  ur: {
    tagline: '— میرا شہر، میری آواز، ہماری تبدیلی —',
    subtagline: 'دیکھیں۔ رپورٹ کریں۔ حل پائیں۔',
    citizen: 'شہری',
    register: 'رجسٹریشن',
    officer: 'افسر',
    login: 'لاگ ان کریں',
    create_account: 'اکاؤنٹ بنائیں',
    officer_login: 'افسر لاگ ان',
    email_or_phone: 'ای میل یا موبائل نمبر',
    password: 'پاس ورڈ',
    full_name: 'پورا نام',
    ward_area: 'وارڈ / علاقہ',
    enter_password: 'پاس ورڈ درج کریں',
    report_problem: 'مسئلہ رپورٹ کریں',
    report_desc: 'تصویر • مقام • تفصیل',
    my_reports: 'میری رپورٹس',
    nearby_issues: 'قریبی مسائل',
    safety_sos: 'خواتین کا تحفظ SOS',
    settings: 'ترتیبات',
    logout: 'لاگ آؤٹ',
    whats_wrong: 'آپ کے علاقے میں کیا مسئلہ ہے؟',
    recent_issues: 'قریبی حالیہ مسائل',
    view_all: 'سب دیکھیں',
    select_language: 'زبان منتخب کریں',
    profile: 'پروفائل',
    activity: 'میری سرگرمی',
    preferences: 'ترجیحات',
    account: 'اکاؤنٹ',
    language: 'زبان',
    notifications: 'اطلاعات',
    privacy: 'رازداری',
    edit_profile: 'پروفائل تبدیل کریں',
    change_password: 'پاس ورڈ تبدیل کریں',
    sos_history: 'SOS تاریخ',
  },
}

interface LanguageState {
  currentLanguage: string
  setLanguage: (code: string) => void
  t: (key: string) => string
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      currentLanguage: 'en',
      setLanguage: (code: string) => set({ currentLanguage: code }),
      t: (key: string) => {
        const lang = get().currentLanguage
        return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en?.[key] || key
      },
    }),
    {
      name: 'fmc_language',
    }
  )
)
